CREATE DATABASE ecommerce_project;
USE ecommerce_project;
DESCRIBE sessions;
SELECT 
    customer_segment, 
    COUNT(*) AS user_count, 
    ROUND(AVG(cart_to_view_ratio), 4) AS avg_intent_score 
FROM sessions 
GROUP BY customer_segment
ORDER BY avg_intent_score DESC;
SELECT 
    product_category_viewed,
    COUNT(session_id) AS total_sessions,
    SUM(added_to_cart) AS total_cart_adds,
    SUM(purchased) AS total_orders,
    -- Calculating how many people who added to cart actually finished the purchase
    ROUND(SUM(purchased) * 100.0 / NULLIF(SUM(added_to_cart), 0), 2) AS cart_conversion_pct
FROM sessions
GROUP BY product_category_viewed
ORDER BY cart_conversion_pct DESC;
SELECT 
    session_id, 
    traffic_source, 
    device_type, 
    pages_viewed, 
    time_on_site_minutes
FROM sessions
WHERE customer_segment = 1  -- This was the highest intent segment
  AND purchased = 0         -- But they didn't buy
  AND added_to_cart = 1     -- And they had items in their cart
ORDER BY time_on_site_minutes DESC
LIMIT 10;
SELECT 
    customer_segment,
    traffic_source,
    device_type,
    ROUND(AVG(pages_viewed), 2) AS avg_pages,
    ROUND(AVG(time_on_site_minutes), 2) AS avg_minutes,
    SUM(added_to_cart) AS cart_adds,
    SUM(purchased) AS conversions,
    -- This shows the "Leakage": People who added to cart but dropped off
    ROUND((1 - (SUM(purchased) * 1.0 / NULLIF(SUM(added_to_cart), 0))) * 100, 2) AS leakage_rate
FROM sessions
WHERE customer_segment IN (1, 2) -- Comparing the Best vs. the Opportunity
GROUP BY customer_segment, traffic_source, device_type
ORDER BY customer_segment, leakage_rate DESC;
USE ecommerce_project;

SELECT 
    country,
    device_type,
    SUM(purchased) AS total_sales,
    -- Window Function: (Current Group Sales / Total Global Sales) * 100
    ROUND(
        SUM(purchased) * 100.0 / SUM(SUM(purchased)) OVER(), 
        2
    ) AS pct_contribution_to_revenue,
    -- Ranking countries by their sales performance
    DENSE_RANK() OVER(ORDER BY SUM(purchased) DESC) AS revenue_rank
FROM sessions
GROUP BY country, device_type
ORDER BY total_sales DESC;
SELECT 
    customer_segment,
    SUM(purchased) AS segment_sales,
    COUNT(session_id) AS total_sessions,
    -- Calculating the 'Yield' (Sales per Session)
    ROUND(SUM(purchased) * 1.0 / COUNT(session_id), 4) AS revenue_per_session,
    -- Percentage of total revenue generated by this specific ML segment
    ROUND(
        SUM(purchased) * 100.0 / SUM(SUM(purchased)) OVER(), 
        2
    ) AS segment_revenue_share_pct
FROM sessions
GROUP BY customer_segment
ORDER BY segment_revenue_share_pct DESC;